name: Publish Package to npmjs
on:
  push:
    tags:
      - 'v*'

jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: read
      id-token: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
      
      - name: Set up Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: "latest"
  
      - name: Install dependencies
        run: |
            bun install
  
      - name: Build
        run: |
            bun run build

      - name: Publish to NPM
        id: publish
        uses: JS-DevTools/npm-publish@v3
        with:
          token: ${{ secrets.NPM_TOKEN }}
          dry-run: false
          provenance: true

      - name: Post-publish
        if: ${{ steps.publish.outputs.type }}
        run: |
          echo "Published ${{ steps.publish.outputs.type }} version: ${{ steps.publish.outputs.version }}"